# Generated by Django 3.2.4 on 2021-11-12 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='realtor_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
